language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --dev
  - export PATH=./bin/:$PATH

script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.3" ]; then phing test; else phing coverage ; fi;'

after_script:
  - php ./bin/coveralls -v
