language: php
os: linux
dist: trusty

services:
  - mysql

php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source
  - export PATH=./bin/:$PATH
  - mysql -u root < ./tests/initdb.sql

script:
  - php ./vendor/bin/phpunit --testsuite unit

after_script:
  - php ./bin/coveralls -v
