language: php
os: linux
dist: trusty

services:
  - mysql

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true

addons:
  sauce_connect: true
  hosts:
  - mysite.dev
  - www.mysite.dev

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - export PATH=./bin/:$PATH
  - mysql -u root < ./tests/initdb_mysql.sql
  - createdb prado_unitest
  - psql -a -w prado_unitest -f ./tests/initdb_pgsql.sql 
  - export SAUCE_BUILD=$TRAVIS_BUILD_NUMBER
  - export SAUCE_TUNNEL_IDENTIFIER=$TRAVIS_JOB_NUMBER
  - php -S 0.0.0.0:8888 &
  - sleep 3

script:
  - php ./vendor/bin/phpunit --testsuite unit
