name: Prado
on: [push, pull_request]
jobs:
  prado:
    name: Prado
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, dom, intl, json, mbstring, memcached, pdo_mysql, pdo_pgsql, openssl, pcre, spl, zlib
          tools: php-cs-fixer, phpstan, cs2pr

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Validate code syntax using php-cs-fixer
        run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Validate code using phpstan
        run: phpstan analyse --error-format=checkstyle | cs2pr

      - name: Setup mysql service
        run: |
          sudo systemctl start mysql.service
          mysql -uroot -proot < ./tests/initdb_mysql.sql

      - name: Setup postgres service
        run: |
          createdb -h 127.0.0.1 -U postgres prado_unitest
          psql -h 127.0.0.1 -U postgres -a -w prado_unitest -f ./tests/initdb_pgsql.sql
        env:
          PGPASSWORD: postgres

      - name: Run Unit Tests
        run: |
          composer unittest

      - name: Run Functional Tests
        run: |
          ACTION_BASE_PATH=`pwd`
          sudo ln -s "$ACTION_BASE_PATH" /var/www/html/prado-master
          cd /var/www/html/
          sudo git clone https://github.com/pradosoft/prado-demos.git prado-demos
          cd prado-demos
          sudo composer install
          sudo mv vendor/pradosoft/prado vendor/pradosoft/prado-stock
          sudo ln -s "$ACTION_BASE_PATH" vendor/pradosoft/prado
          cd "$ACTION_BASE_PATH"
          sudo nohup php -S 0.0.0.0:80 -t /var/www/html/ > phpd.log 2>&1 &
          TEST_HOST=172.17.0.1 composer functionaltest